language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("Discretizers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
